### ISSUE TITLE
[Feature] 가게 찾기 API 구현

### ISSUE THREAD

**Issue by yeop0740** [KUSITMS-Team-A/Backend#15]
## 💡 이슈 내용
가게 찾기 페이지에서 필요한 API 구현

## To-do
- [x] 가게 검색 및 조회
- [x] 가게 픽하기/되돌리기
- [x] 가게 상세 정보 조회

## ETC
