### ISSUE TITLE
[Feature] S3로 이미지를 관리한다.

### ISSUE THREAD

**Issue by pdohyung** [KUSITMS-Team-A/Backend#16]
## 💡 이슈 내용
- S3로 이미지를 업로드하고 삭제하는 기능을 추가합니다.

## To-do
- [x] S3 기능을 사용하기 위한 설정 추가
- [x] 파일 업로드, 삭제 기능 추가
- [x] 사용자 도메인과 연동

## ETC
