### ISSUE TITLE
[Feature] 팝업 기능 구현

### ISSUE THREAD

**Issue by pdohyung** [KUSITMS-Team-A/Backend#21]
## 💡 이슈 내용
팝업 기능을 구현합니다.

## To-do
- [x] 팝업 생성 기능
- [x] 팝업 조회 기능
- [x] 팝업 삭제 기능

## ETC
