### ISSUE TITLE
[Fix] 제휴 가게 조회 API 스펙 변경

### ISSUE THREAD

**Issue by yeop0740** [KUSITMS-Team-A/Backend#35]
## 💡 이슈 내용
제휴 가게 상세 조회 주소 정보 추가

## To-do
- [x] 제휴 가게 상세 조회 수정
- [x] 제휴 가게 목록 조회 조건과 혜택 형식 수정
- [x] 제휴 등록 방식 수정(FIX, RATE, MENU에 따라 다른 방식 선택)

## ETC
